# Generated by Django 3.1.1 on 2020-09-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfers',
            name='type',
        ),
        migrations.AddField(
            model_name='transfers',
            name='counterparty_type',
            field=models.CharField(choices=[('income', 'INCOME'), ('outcome', 'OUTCOME')], default='receiver', max_length=7),
        ),
        migrations.AddField(
            model_name='transfers',
            name='transfer_type',
            field=models.CharField(choices=[('income', 'INCOME'), ('outcome', 'OUTCOME')], default='outcome', max_length=7),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BTC', 'BTC'), ('RUR', 'RUR'), ('GBP', 'GBP')], default='USD', max_length=3),
        ),
    ]
