# Generated by Django 3.1.1 on 2020-09-02 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200902_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='counterparty_acccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
