# Generated by Django 3.1.1 on 2020-09-02 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200902_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfers',
            old_name='counterparty_acccount',
            new_name='counterparty_account',
        ),
    ]
