# Generated by Django 3.1.1 on 2020-09-02 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200902_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfers',
            name='counterparty_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='counterparty_account', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
