# Generated by Django 3.1.1 on 2020-09-03 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200902_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='advuser',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.currency', to_field='name'),
        ),
    ]
