# Generated by Django 3.1.1 on 2020-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200903_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3),
        ),
    ]
