# Generated by Django 3.1.1 on 2020-09-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200903_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.currency', to_field='name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
