# Generated by Django 3.1.1 on 2020-09-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200903_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
