# Generated by Django 3.1.1 on 2020-09-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200903_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='password',
            field=models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
