# Generated by Django 3.1.1 on 2020-09-03 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200903_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('basic', 'BASIC'), ('secondary', 'SECONDARY')], default='SECONDARY', max_length=9),
        ),
        migrations.AddField(
            model_name='currency',
            name='multiplicity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='currency',
            name='short_name',
            field=models.CharField(blank=True, max_length=3, unique=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='currency',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.currency', to_field='short_name'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
