# Generated by Django 3.1.1 on 2020-09-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_currency_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='course',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=8),
        ),
    ]
