# Generated by Django 3.1.1 on 2020-09-09 00:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200904_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfers',
            name='currency',
            field=models.ForeignKey(default='USD', on_delete=django.db.models.deletion.PROTECT, to='api.currency', to_field='short_name'),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='advuser',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.currency', to_field='short_name'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='counterparty_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_account', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
