# Generated by Django 3.1.1 on 2020-09-10 17:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20200909_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='currency',
            name='code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='course',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='currency',
            name='multiplicity',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='currency',
            name='short_name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(8, 2)]),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='counterparty_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_account', to=settings.AUTH_USER_MODEL, to_field='username', validators=[django.core.validators.EmailValidator()]),
        ),
    ]
