# Generated by Django 3.1.1 on 2020-09-11 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0002_auto_20160226_1747'),
        ('api', '0020_auto_20200910_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='key',
            field=models.OneToOneField(default='123', on_delete=django.db.models.deletion.PROTECT, to='authtoken.token'),
        ),
        migrations.AlterField(
            model_name='transfers',
            name='counterparty_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counterparty_account', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
