# Generated by Django 3.1.1 on 2020-09-11 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20200911_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='key',
        ),
    ]
